# Generated by Django 3.0.8 on 2020-07-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_featured'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
